MODEL:
  NUM_CLASSES: 2
INPUT:
  IMAGE_WIDTH: 800
  IMAGE_HEIGHT: 600
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 100000
  LR_STEPS: [60000, 80000]
  GAMMA: 0.1
  BATCH_SIZE: 8
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_voc0712'